name: "CI/CD"
on: [push]
jobs:
  command:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: install
        run: yarn
      - name: setup prisma
        run: yarn --cwd src/server/book-inventory-server prisma:generate
      - name: jest
        run: TZ=Asia/Tokyo yarn test
